# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: R4C60N
email: rachan@interia.pl
description: Free speach
baseurl: "/gravity-now" # the subpath of your site, e.g. /blog
url: "https://magnetofield.github.io" # the base hostname & protocol for your site
twitter_username: rachan
github_username:  magnetofield
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
